[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "always"

# Don't set PORT - Railway will provide it automatically

[[deploy.envVars]]
name = "TRANSPORT"
value = "streamable-http"

[[deploy.envVars]]
name = "HOST"
value = "0.0.0.0"

# Enable minimal logging to stdout for Railway
[[deploy.envVars]]
name = "MCP_LOGGING_STDOUT"
value = "true"

# Set minimal verbosity
[[deploy.envVars]]
name = "MCP_VERBOSE"
value = "true"
