[build]
builder = "dockerfile"

[deploy]
startCommand = "mcp-atlassian --transport streamable-http --host 0.0.0.0 --port 8000 --read-only -vv"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "always"

# Railway will automatically expose the port from EXPOSE instruction in Dockerfile
# But we can be explicit about it
[[deploy.envVars]]
name = "PORT"
value = "8000"

[[deploy.envVars]]
name = "TRANSPORT"
value = "streamable-http"

[[deploy.envVars]]
name = "HOST"
value = "0.0.0.0"

# Enable minimal logging to stdout for Railway
[[deploy.envVars]]
name = "MCP_LOGGING_STDOUT"
value = "true"

# Set minimal verbosity
[[deploy.envVars]]
name = "MCP_VERBOSE"
value = "true"
